### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by englianhu** [algoquant/HighFreq#1]
```r
Installation status:  TRUE . Removing the file:
 C:\Users\scibr\AppData\Local\Temp\RtmpUVvpQn/Rtools35.exe 
 (In the future, you may keep the file by setting keep_install_file=TRUE) 
> devtools::install_github('algoquant/HighFreq', force=TRUE)
Downloading GitHub repo algoquant/HighFreq@master
from URL https://api.github.com/repos/algoquant/HighFreq/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.3,3.4,3.5)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installation failed: Could not find build tools necessary to build HighFreq
```

I wondered why I had just installed latest version `RTools35.exe`, installation of other packages working fine.

**Comment by algoquant** [comment]
I'm also running R version 3.5.1 and Rtools version 3.5.0.4
I've installed many packages with C++ code from source, including HighFreq.

Try installing the development version of devtools from GitHub:
devtools::install_github("r-lib/devtools")

You can read more about solutions to this problem here:
https://github.com/r-lib/devtools/issues/1772
https://community.rstudio.com/t/rtools-not-recognized-r3-5-1-rtools-3-5/11311
