### ISSUE TITLE
Registration at CRAN

### ISSUE THREAD

**Issue by waynelapierre** [algoquant/HighFreq#3]
I am super interested in this package, what's holding it from being registered at CRAN?

**Comment by algoquant** [comment]
Wayne,
I'm glad to hear that you like the package HighFreq.
I haven't migrated it to CRAN because it's still under heavy development.  And it has grown to the point where I may split off some parts of it to a new package. 
I would very much like to hear your suggestions and requests regarding package HighFreq.

Best,  Jerzy

**Comment by waynelapierre** [comment]
I will use this package on the Options Price Reporting Authority (OPRA) data and a foreign exchange tick-by-tick data for the next 4 months. I will let you know what I think about your package. Thank you for your effort in developing this package!
